import { openDatabaseSync } from 'expo-sqlite';
import { drizzle } from 'drizzle-orm/expo-sqlite';
import { migrate } from 'drizzle-orm/expo-sqlite/migrator';

import * as schema from './schema';

// The migrations barrel is generated by drizzle-kit (expo driver).
// It exports { journal, migrations } for the Drizzle migrator.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const migrationBundle = require('./migrations/migrations') as {
  default: {
    journal: {
      entries: { idx: number; when: number; tag: string; breakpoints: boolean }[];
    };
    migrations: Record<string, string>;
  };
};

const sqlite = openDatabaseSync('tideline.db');

export const db = drizzle(sqlite, { schema });

/**
 * Applies any pending Drizzle migrations.
 * Call once on app mount; subsequent calls are idempotent.
 */
export async function runMigrations(): Promise<void> {
  await migrate(db, migrationBundle.default);
}
